// ─────────────────────────────────────────────────────────────────────────────
// _alias-skus.js — put a SKU on a packing line by asking the DATABASE which
// vial the line resolved to, instead of re-reading the name and guessing again.
// Added 2026-08-20.
//
// 🚨 THE PROBLEM THIS FIXES. SKUs already render on the Orders table and the
// invoice, and on real data they resolved for **48 of 136 sold lines**. The 88
// that printed bare included exactly the ambiguous ones the feature exists for:
//   16 lines  TESAMORELIN / IPAMORELIN "PHOENIX BLEND"   (two Phoenix strengths)
//    6 lines  GHK-CU / BPC-157 / TB-500 "GLOW BLEND"
//    5 lines  GHK-CU / BPC-157 / TB-500 / KPV "KLOW BLEND"
//    2 lines  BPC-157 / TB-500 "WOLVERINE BLEND"         (two Wolverine strengths)
// Square-era names, none of which `nameToId()` will touch.
//
// 🔑 AND IT IS RIGHT THAT nameToId() REFUSES THEM. "WOLVERINE BLEND" with no
// strength is genuinely ambiguous, and a SKU that might be wrong is worse than
// none — its only job is to be the thing you trust when checking a vial.
// Guessing was never the answer. Asking something that already knows is.
//
// 🔑 THE DATABASE ALREADY DECIDED. `resolve_variant()` matched that same string
// against `variant_aliases` to work out which vial to DEDUCT FROM STOCK, and
// migration 020 pinned every storefront variant so nothing resolves by
// guesswork. So the alias table holds the answer, arrived at once, deliberately.
//
// 🚨 THE PROPERTY THAT MAKES THIS SAFE, AND WHY IT BEATS PARSING: the SKU shown
// is the SKU of the vial whose stock actually moved. If the alias were wrong,
// the ledger is wrong too — and printing the same answer makes that disagreement
// visible on the packing slip instead of hiding it behind a blank. A displayed
// SKU derived independently could contradict the books and look authoritative.
// Audited 2026-08-20 across all 57 aliases: 48 agree with nameToId(), 4 are ones
// it refuses, 5 are variants with no site id — and ZERO disagree.
// test-alias-skus.mjs pins that "zero disagreements" invariant.
//
// ⚠️ FAILS SOFT, ALWAYS. If this cannot be fetched, callers fall back to exactly
// today's name parsing. A SKU is a convenience on a picking list; the orders
// list is how Frank ships, and it must never fail to draw because a lookup
// table was unreachable.
// ─────────────────────────────────────────────────────────────────────────────

const { CATALOG, packingLine } = require('./_catalog');

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;
const TIMEOUT_MS = 6000;

/**
 * An exact mirror of the database's `norm_name(text)`:
 *
 *   btrim(regexp_replace(lower(regexp_replace(t, '[^a-zA-Z0-9]+', ' ', 'g')),
 *                        '\s+', ' ', 'g'))
 *
 * 🚨 IT MUST STAY EXACT. `variant_aliases.alias_norm` is generated by that
 * function, and matching on anything looser would attach a SKU to a line the
 * database did NOT resolve — which is the one failure mode worse than a blank
 * SKU, because it looks like an answer. Anything stricter silently loses rows.
 * Note the order: punctuation becomes spaces BEFORE lowercasing, and the
 * character class is ASCII-only in both languages.
 */
function normName(t) {
  if (t === null || t === undefined) return '';
  return String(t)
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .trim();
}

async function fetchJson(path) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
  try {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/${path}`, {
      headers: {
        apikey: SUPABASE_KEY,
        Authorization: `Bearer ${SUPABASE_KEY}`,
        Accept: 'application/json',
      },
      signal: controller.signal,
    });
    if (!res.ok) return null;
    const rows = await res.json();
    return Array.isArray(rows) ? rows : null;
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
}

/**
 * normalised alias → { sku, label } for every alias the database can identify.
 *
 * 🔑 TWO SOURCES, NEVER OVERLAPPING, which is what stops them disagreeing:
 *   • On the site  → CATALOG owns the SKU and the specific packing label.
 *   • Retired      → `variants.sku` owns it (migration 030). Those products are
 *                    deliberately absent from CATALOG, because being in CATALOG
 *                    is what makes something buyable — adding Retatrutide 12mg
 *                    there to give it a SKU would put it back on sale.
 * Migration 030 enforces the split: variants.sku is NULL for anything on the
 * site, so a product can never carry two SKUs.
 *
 * 🔑 A RETIRED LINE KEEPS ITS STORED NAME (`label: null`). CATALOG's labels
 * spell out a blend's full composition, which is worth substituting in; a
 * retired product has no such label, and rewriting history from a product row
 * would change what an old order says it sold for no benefit. Only the SKU is
 * added.
 *
 * Returns null — never an empty Map — when the lookup fails, so a caller can
 * tell "nothing is mapped" from "we could not ask".
 */
async function fetchAliasLines() {
  if (!SUPABASE_URL || !SUPABASE_KEY) return null;
  const rows = await fetchJson(
    'variant_aliases?select=alias_norm,variants(site_catalog_id,sku)&order=alias_norm',
  );
  if (!rows) return null;

  const map = new Map();
  for (const r of rows) {
    if (!r.alias_norm || !r.variants) continue;
    const { site_catalog_id: id, sku } = r.variants;
    const entry = id ? CATALOG[id] : null;
    if (entry) {
      map.set(r.alias_norm, { sku: entry.sku, label: entry.label });
    } else if (sku) {
      // Retired: a SKU, and the line keeps whatever it was sold as.
      map.set(r.alias_norm, { sku, label: null });
    }
  }
  return map;
}

/**
 * The packing line for a stored name: what to print, and the SKU to check the
 * vial against.
 *
 * 🚨 THE DATABASE IS ASKED FIRST. `resolve_variant()` matched this same string
 * to decide which vial to deduct from stock, so its answer names the vial that
 * actually left the shelf. Falling back to `packingLine`'s own name parsing
 * only when the database has nothing to say keeps every line that already
 * worked working, unchanged.
 */
function packingLineFor(aliasLines, name) {
  const hit = aliasLines ? aliasLines.get(normName(name)) : null;
  if (hit) return { sku: hit.sku, label: hit.label || name };
  return packingLine(name);
}

module.exports = { fetchAliasLines, packingLineFor, normName };
