// ─────────────────────────────────────────────────────────────────────────────
// Netlify Function: create-order.js
// Added 2026-08-17 — ring up an in-person sale here instead of opening Square.
//
//   POST { client_uid, purpose, payment_state, party_id, customer, lines, ... }
//
// 🔑 party_id WINS OVER customer{}. create_manual_order only falls back to
// matching on email when party_id is null, and inserts a new party when that
// finds nothing. Since most counter customers pay by Zelle and have no email,
// that fallback was giving a returning buyer a NEW party row every sale — and
// reorder cadence is per party, so each duplicate silently reset it. The picker
// in admin.html sends the real id; customer{} stays for genuinely new people.
//
// This is the piece that actually removes work. The website has recorded its own
// orders since Square was deactivated; a sale at the door still meant walking to
// Square. Now it doesn't.
//
// 🔑 IDEMPOTENT ON client_uid, generated by the page per sale attempt. A double
// click, a flaky connection, a retry — none of them ring the sale twice.
// stock_ledger is append-only, so a duplicated sale cannot be deleted, only
// offset by a visible correction. Making that impossible beats detecting it.
//
// 🔑 PURPOSE IS REQUIRED (rule 5). Frank's own vials and give-aways move real
// stock but are NOT revenue — 20 such orders are worth -$739.20 in the history.
// Defaulting quietly to SALE is how they end up counted.
//
// ⚠️ This writes ONLY to the dashboard. It does not create a Square order, by
// design — the dashboard is replacing Square as the record. While Square is
// still being run in parallel, an in-person sale recorded here will not appear
// there.
//
// 🔐 Token-gated.
// ─────────────────────────────────────────────────────────────────────────────

const { verifyToken } = require('./_auth-token');

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;
const TIMEOUT_MS = 10000;

const PURPOSES = ['SALE', 'INTERNAL', 'COMP', 'SAMPLE'];
const PAY_STATES = ['PAID', 'AWAITING_PAYMENT'];
// How the money arrived. HOUSE_ACCOUNT means it has not: the sale goes on the
// customer's tab and is settled later through record-payment.js.
const TENDERS = ['ZELLE', 'CASH', 'CARD', 'BANK_TRANSFER', 'HOUSE_ACCOUNT', 'OTHER'];
const CHANNELS = ['POS', 'MANUAL'];
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

async function rpc(fn, args) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
  let res, body;
  try {
    res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/${fn}`, {
      method: 'POST',
      headers: {
        apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}`,
        'Content-Type': 'application/json', Accept: 'application/json',
      },
      body: JSON.stringify(args), signal: controller.signal,
    });
    body = await res.text();
  } finally { clearTimeout(timer); }
  if (!res.ok) {
    let message;
    try { message = JSON.parse(body).message; } catch { /* not json */ }
    const err = new Error(message || `Supabase ${res.status}`);
    err.status = message ? 400 : 502;
    throw err;
  }
  return body ? JSON.parse(body) : null;
}

// Money is integer cents end to end. A float here is a bug, not a convenience.
// Is this customer allowed to buy on credit? Migration 028 records the decision
// on the party; this is where it is enforced.
//
// 🔑 FAILS CLOSED, and only here. Everywhere else in this file a Supabase
// wobble should not stop a sale — "a till must always take money" — but this is
// not taking money, it is extending credit. If the permission cannot be read,
// the honest answer is "ring it up as paid", not "assume they are good for it".
//
// ⚠️ It deliberately does NOT block on the credit limit. Over-limit is a
// warning at the counter, not a refusal — Frank standing in front of a customer
// is better placed to make that call than a column is.
async function gateHouseAccount(partyId) {
  let rows;
  try {
    rows = await sbGet(`parties?select=id,display_name,merged_into_id,house_account_enabled&id=eq.${partyId}`);
  } catch (err) {
    // The column arrives with 028. Until then, say which migration is missing
    // rather than silently letting every charge through.
    const missing = /house_account_enabled/.test(err.detail || err.message || '');
    return { ok: false, status: missing ? 503 : 502, body: {
      error: missing
        ? 'House-account permissions are not set up in the database yet.'
        : 'Could not check whether that customer has a house account — the sale was not recorded.',
      hint: missing
        ? 'Apply replace-square-phase1/fixes/028-house-account-grants.sql, then reload.'
        : 'Try again, or ring it up as paid.',
    } };
  }

  if (!rows.length) {
    return { ok: false, status: 404, body: { error: 'That customer no longer exists — pick again' } };
  }
  const p = rows[0];
  if (p.merged_into_id) {
    return { ok: false, status: 409, body: {
      error: 'That customer record was merged into another one — pick the surviving record.' } };
  }
  if (!p.house_account_enabled) {
    return { ok: false, status: 403, body: {
      error: `${p.display_name || 'That customer'} does not have a house account.`,
      hint: 'Open them on the Customers tab and give them one, or take payment now.' } };
  }
  return { ok: true };
}

async function sbGet(path) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
  try {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/${path}`, {
      headers: {
        apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}`, Accept: 'application/json',
      },
      signal: controller.signal,
    });
    const body = await res.text();
    if (!res.ok) {
      const err = new Error(`Supabase returned ${res.status}`);
      err.detail = body.slice(0, 400);
      throw err;
    }
    return JSON.parse(body);
  } finally {
    clearTimeout(timer);
  }
}

function cents(v, label) {
  if (v === null || v === undefined || v === '') return 0;
  if (typeof v !== 'number' || !Number.isInteger(v) || v < 0) {
    throw Object.assign(new Error(`${label} must be a whole number of cents, not below zero`), { status: 400 });
  }
  return v;
}

const text = (v, max) => {
  if (v === null || v === undefined) return null;
  const s = String(v).trim();
  return s === '' ? null : s.slice(0, max);
};

exports.handler = async (event) => {
  const headers = { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' };

  const SECRET = process.env.ADMIN_TOKEN_SECRET;
  if (!SECRET) {
    return { statusCode: 500, headers, body: JSON.stringify({ error: 'ADMIN_TOKEN_SECRET not configured.' }) };
  }
  const authHeader = event.headers.authorization || event.headers.Authorization || '';
  if (!verifyToken(SECRET, authHeader.replace(/^Bearer\s+/i, ''))) {
    return { statusCode: 401, headers, body: JSON.stringify({ error: 'Unauthorized' }) };
  }
  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, headers, body: JSON.stringify({ error: 'Method not allowed' }) };
  }
  if (!SUPABASE_URL || !SUPABASE_KEY) {
    return {
      statusCode: 500, headers,
      body: JSON.stringify({
        error: 'Supabase is not configured.',
        detail: 'Set SUPABASE_URL and SUPABASE_SERVICE_KEY in Netlify → Site settings → Environment variables, then redeploy.',
      }),
    };
  }

  let input = {};
  try { input = JSON.parse(event.body || '{}'); } catch {
    return { statusCode: 400, headers, body: JSON.stringify({ error: 'Body is not valid JSON' }) };
  }

  try {
    const purpose = String(input.purpose || '').toUpperCase();
    if (!PURPOSES.includes(purpose)) {
      return { statusCode: 400, headers, body: JSON.stringify({
        error: 'Say what this order is: a sale, your own use, or a give-away' }) };
    }
    let paymentState = String(input.payment_state || 'AWAITING_PAYMENT').toUpperCase();
    if (!PAY_STATES.includes(paymentState)) {
      return { statusCode: 400, headers, body: JSON.stringify({ error: 'Unknown payment state' }) };
    }
    const tenderType = String(input.tender_type || 'ZELLE').toUpperCase();
    if (!TENDERS.includes(tenderType)) {
      return { statusCode: 400, headers, body: JSON.stringify({ error: 'Unknown payment method' }) };
    }

    // ── Charging a sale to someone's tab ─────────────────────────────────────
    // 🔑 A house-account sale is PAID. That reads oddly and is right: the sale
    // is complete and settled against the tab, which is what makes it count as
    // revenue — Frank's decision, and what the database already did with the
    // historical house-account tenders. What is still owed lives in
    // v_house_account_balance, not in the order's payment state. Leaving it
    // AWAITING_PAYMENT would mean create_manual_order wrote no tender at all,
    // and a tab with no charge on it is a debt nobody can see.
    if (tenderType === 'HOUSE_ACCOUNT') {
      if (purpose !== 'SALE') {
        return { statusCode: 400, headers, body: JSON.stringify({
          error: 'Only a sale can go on a house account — your own use and give-aways are not owed to anyone' }) };
      }
      // A tab has to belong to someone. create_manual_order will create the
      // party from customer{} if it is new, and migration 025's trigger attaches
      // the charge to whoever that turns out to be — but an unnamed walk-in
      // would open a tab nobody could ever be asked to settle.
      const named = input.party_id || String(input.customer?.name || '').trim();
      if (!named) {
        return { statusCode: 400, headers, body: JSON.stringify({
          error: 'Pick or name the customer whose house account this goes on' }) };
      }

      // ── The gate (added 2026-08-20, migration 028) ─────────────────────────
      // 🚨 CREDIT IS GRANTED PER PERSON AND ENFORCED HERE. The New sale form
      // hides the option for anyone without an account, but a rule that lives
      // only in the page it is drawn on is not a rule — this endpoint is
      // reachable directly, and the page can be stale about who was revoked
      // five minutes ago.
      //
      // 🔑 A BRAND-NEW CUSTOMER CANNOT BE CHARGED TO A TAB. There is nobody to
      // have granted credit to yet: create_manual_order would insert the party
      // and the charge in the same breath, which is precisely the decision
      // Frank asked to stop being automatic. Sell it as paid, or grant the
      // account first — the message says so.
      if (!input.party_id) {
        return { statusCode: 403, headers, body: JSON.stringify({
          error: 'A new customer cannot start on a house account.',
          hint: 'Ring this sale up as paid, or add them on the Customers tab and give them a house account there first.' }) };
      }
      const gate = await gateHouseAccount(input.party_id);
      if (!gate.ok) return { statusCode: gate.status, headers, body: JSON.stringify(gate.body) };

      paymentState = 'PAID';
    }
    const channel = String(input.channel || 'POS').toUpperCase();
    if (!CHANNELS.includes(channel)) {
      return { statusCode: 400, headers, body: JSON.stringify({ error: 'Unknown channel' }) };
    }

    // An existing customer picked from the dropdown. Optional — a genuinely new
    // customer still arrives as customer{} — but if one is sent it must be a real
    // uuid. Rejecting a malformed id here beats handing it to Postgres to cast
    // and fail with something nobody standing at a counter can act on.
    const partyId = input.party_id ? String(input.party_id) : null;
    if (partyId && !UUID.test(partyId)) {
      return { statusCode: 400, headers, body: JSON.stringify({ error: 'That customer selection is not valid — pick again' }) };
    }

    const lines = Array.isArray(input.lines) ? input.lines : [];
    if (!lines.length) {
      return { statusCode: 400, headers, body: JSON.stringify({ error: 'Add at least one product' }) };
    }
    if (lines.length > 100) {
      return { statusCode: 400, headers, body: JSON.stringify({ error: 'Too many lines' }) };
    }

    const cleanLines = lines.map((l, i) => {
      if (!UUID.test(String(l.variant_id || ''))) {
        throw Object.assign(new Error(`Line ${i + 1}: pick a product`), { status: 400 });
      }
      const qty = Number(l.quantity);
      if (!Number.isFinite(qty) || qty <= 0 || qty > 1000) {
        throw Object.assign(new Error(`Line ${i + 1}: quantity must be between 1 and 1000`), { status: 400 });
      }
      return {
        variant_id: l.variant_id,
        quantity: qty,
        unit_price_cents: cents(l.unit_price_cents, `Line ${i + 1} price`),
        name: text(l.name, 200),
      };
    });

    const result = await rpc('create_manual_order', {
      p: {
        // Generated by the page per sale attempt — the guard against a retry
        // ringing the same sale twice.
        client_uid: text(input.client_uid, 100),
        purpose,
        payment_state: paymentState,
        // create_manual_order defaults this to ZELLE; it decides the tender row
        // it writes for a PAID sale, which is what a house-account charge is.
        tender_type: tenderType,
        channel,
        placed_at: input.placed_at || null,
        discount_cents: cents(input.discount_cents, 'Discount'),
        tax_cents: cents(input.tax_cents, 'Tax'),
        shipping_cents: cents(input.shipping_cents, 'Shipping'),
        note: text(input.note, 2000),
        // Set when an existing customer was picked. create_manual_order only
        // falls back to email-matching (and then to inserting a new party) when
        // this is null, so sending it is what keeps a returning buyer on one row.
        party_id: partyId,
        customer: {
          name: text(input.customer?.name, 200),
          email: text(input.customer?.email, 200),
          phone: text(input.customer?.phone, 60),
        },
        lines: cleanLines,
      },
    });

    return { statusCode: 200, headers, body: JSON.stringify(result) };
  } catch (err) {
    const timedOut = err.name === 'AbortError';
    const msg = timedOut ? `Supabase timed out after ${TIMEOUT_MS}ms` : err.message;
    if (!err.status || err.status >= 500) console.error('create-order error:', msg);
    return { statusCode: timedOut ? 504 : (err.status || 500), headers, body: JSON.stringify({ error: msg }) };
  }
};
